### ISSUE TITLE
Test Version for TB 128

### ISSUE THREAD

**Issue by jimmutter** [opto/Expression-Search-NG#122]
Requesting an update on when Expression Search NG will be compatible with Thunderbird 128+.  
I appreciate that there's probably some real work to make this happen and I'm happy to be the first to contribute some $$$ if that's what it takes.

**Comment by opto** [comment]
many thanks. Actually, I did some testing in the last days and was surprised that "nothing" was working. In addition to the standard change in the module system, which needs similiar code changes in all my addons, it seems they have done recoding on the search filters.
Today, I did a few hours of reading "their" new code and understanding what they changed. All in all, it is manageable, but needs some specific  changes, as it looks like.

So the update will come, but needs some time.

Klaus

**Comment by AddisZone** [comment]
Notice:
Here it's not even working with [BB *115*.13 (Portable)](https://www.betterbird.eu/downloads/WindowsPortable/BetterbirdPortable-115.13.0-bb30.en-US.win64.zip)
There are no search results regardless what filter was entered and the Add-On options page doesn't open.
I went back to [last working BB](https://www.betterbird.eu/downloads/WindowsPortable/BetterbirdPortable-115.12.0-bb29.en-US.win64.zip)
Unfortunately there is still another [flaw](https://github.com/opto/Expression-Search-NG/issues/111#issuecomment-2242428966) in Expression-Search-NG but it's nevertheless a very great tool ! Many thanks for the continuation with the NG version !

**Comment by avegaweiss** [comment]
AddisZone: what's your experience on BB? Never hear of it. Good alternativa?
I've made some changes on the current version of Expression  Serach to make it work on TB115.13 (with some pitfalls, but a working version). You can find it as a reply on issue #119

Opto, can I help somehow in the fixinf for this new releae?

**Comment by AddisZone** [comment]
avegaweiss: I don't see any disadvantages. I found BB accidentially when updating from TB60 to 115 failed. My two IMAP accounts always became disrupted. Due to resulting resync I lost all tags because our MS Exchange server isn't able to store the tags as IMAP keywords. :(  Because there are everywhere only positive tests I gave BB a try. It didn't solve my problem due to almost all is identical to TB. But I stay with it. The structure and update of the portable version is better/easier and one can register the portable as default mail client. Roughly speaking BB = TB with less bugs and more features.

**Comment by terry9873** [comment]
Hi, i have just heard of this extension after I was about to leave Thunderbird (though I have no alternative yet) because the search is utterly defective. Someone said this extension may make it usable again ( I have a lot of mail in local folders). I tried to install but it refused. I assume because it's not ready for latest TB version yet. I will be watching with interest, all the positive reviewers sound like me! :D 
Thanks for your work, hope it can work soon

**Comment by avegaweiss** [comment]
AddisZone:  Just try BB instear ob TB.
So far,all right. Even I can migrate all my folders, just 'pointing' both instalationto same folders.
I use my modified version of Expression Search (see issue #119) and it's working ,with some limitations. Most missed feature: remember filter when changing folders. But everythin else works

**Comment by terry9873** [comment]
Thanks, so to confirm, are you saying I should just switch to Betterbird instead, and then this extension will work? If so, that's useful and i may try BB. thanks

**Comment by avegaweiss** [comment]
Any update on migrating this plugin??

**Comment by avegaweiss** [comment]
@opto ....updates on this? Are you using the plugin?
I 'm not updating to 128 until this plugin works :)
Can I help somehow? I've done some minor bug fixing, but really don't understand the plugin logic. Anyway, if I can help....

**Comment by arkticrainbow** [comment]
I am already on v128 and its a pain to use without NG search. Hope to see an update soon!

**Comment by terry9873** [comment]
'its a pain to use without NG search.'
Can I ask, I haven't used this yet (waiting for 128 compatibility), but I am so disappointed with TB search (since leaving Mac Mail (and Mac entirely). The global search doesn't find stuff I know is in my local folders, and all settings are how they should be. 
Does this plugin make search function better in TB, or make it actually work as it should?!

**Comment by gszathma** [comment]
Hi, I would like to ask, that the compatibility for the actual TB is underway? Can we expect sometimes? (I have donated already twice the great development work). 
Even a limited (basic) functionality would be great to start, as the built in search is very-very limited, this add on gives the competitive edge for TB. We have no news on the process. I am worried. Thank you.

**Comment by opto** [comment]
don't worry, I am onto it and it will definitely come for 128, but is not quite finished yet. I am also still on 115 ...
And many thanks for donating ... Klaus

**Comment by Inserm-CRI-LBI** [comment]
Great to have some news. I can only "cheer from the sidelines" (and donate, which I also did), but thanks in advance for the port to 128. TB is unuseable without it, I wonder how the Mozilla team has not picked it up on it already and implemented it as main feature and rewarded you handsome money for it.

**Comment by arkticrainbow** [comment]
> 'its a pain to use without NG search.' Can I ask, I haven't used this yet (waiting for 128 compatibility), but I am so disappointed with TB search (since leaving Mac Mail (and Mac entirely). The global search doesn't find stuff I know is in my local folders, and all settings are how they should be. Does this plugin make search function better in TB, or make it actually work as it should?!

Hard to generalize but its safe to say you can easily fine tweek your searches with NG. Global search works lets say OK as is in TB but you cannot add filter options (search for specific sender AND receiver AND find specific attachement) and you have to dig through all search results. With NG its much easier since you know who sent it to whom with what attachement, you can pinpoint date intervals and I often times found givin 3-4 filter options gives me only handful (often times the only one) result which I was looking for.

**Comment by opto** [comment]
test version for 128: https://github.com/opto/Expression-Search-NG/releases/tag/v4.0.40

**Comment by superian** [comment]
I haven't tested everything, but the file installed on TB 128.3.1esr and it's searching vastly better than TB's native global search.

Thank you!

**Comment by LAMepelle** [comment]
Thanks, Klaus!

It's working for me but there are two cosmetic things to consider:

1. When I click into the search field, there is a big banner popping up that's called "Search History" but there is no history.
2. In the search field there is a label telling "keyLabelMac", not sure whether it's needed.

Please find a screenshot below:

<img width="2327" alt="expressionsearch" src="https://github.com/user-attachments/assets/3e75b6d2-0f09-4680-aeb2-717023ef0fdd">

**Comment by rg-ch** [comment]
Thanks a lot for  this test version, which seems to work. But I observe  the same issue as LAMapelle above.

**Comment by avegaweiss** [comment]
Great work! Now we can update to 128.....
Same comment: while  recent history could be helpful, is a bit annoying that always pop ups.
Better if you enable with a key (like arrow down)

**Comment by opto** [comment]
@avegaweiss thanks for the proposal.
After searching, arrow down actually jumps down into the search results and displays the first message, so something else would be needed.

As for the cosmetic issues mentioned abovem they will eventually go away.

Klaus

**Comment by rptb1** [comment]
> test version for 128: https://github.com/opto/Expression-Search-NG/releases/tag/v4.0.40

THANK YOU! I can now process my inbox (in reasonable time) again. I will submit issues about anything I find, but after a few hours of use it looks good in Thunderbird 128.3.1esr on Ubuntu 22.04.

**Comment by arkticrainbow** [comment]
Thank you, works well. I have same findings as "LAMepelle" mentioned but nothing major

**Comment by avegaweiss** [comment]
Hi! I'm using now Betterbird instead of Thunderbird.
Plugin is working almost fine. I'm using search folders, and sometimes the search forlder doesn't show the proper content, and I need to go to 'properties' then 'update' to refresh content.

**Comment by opto** [comment]
history can be repositioned or disabled in the next version
