### ISSUE TITLE
Ctrl-Right Click not working anymore

### ISSUE THREAD

**Issue by Phil-ux12** [opto/Expression-Search-NG#69]
Hello, 
As the subject of this issue : None of Ctrl or Shift Right-CLick works : doesn't do anything.
Another issue : The Escape Key deactivates the filtering, but doesn't clear anymore the search field,
Voila, That's all
Thank you for this project wich is very helpful  in finding emails,
Phil

**Comment by Phil-ux12** [comment]
Sorry, I forgot these informations : 
ESNG : 3.8.10
TB : 102.9.1 (64 bits)

**Comment by opto** [comment]
Esc key: works here in 102.12.0  (Win 10 64 bit) in my newest version, coming soon.
ctrl Rightclick: works here as well, but shift rightclick opens a TB popup.

If this is still happening for you, please let me know.

Due to many TB changes, update to TB 115 is a lot of work - donations are very much appreciated, see https://github.com/opto/Expression-Search-NG/issues/72

**Comment by Phil-ux12** [comment]
Thank you very much,
I finally found a workaround : I created a new profile in TB, and then imported all my mail accounts, and reinstalled all my favorite extensions. 
This worked and continue to work for me.

My install :

- TB : 102.12.0 (64 bits)
- ESNG : 3.8.10
- Autofile : 2.0.0
- Fournisseur pour Google Agenda : 102.0.3
- Manually sort folders : 2.3.0
- QuickFolders : 5.16.1
- Signal Spam : 4.1.3
- Signature Switch : 2.15.3
- Theme : Default theme

Hope it will help you.
Thank you,
Phil

**Comment by opto** [comment]
thanks. Also works in TB 115: please try https://github.com/opto/Expression-Search-NG/releases/tag/v4.0.11
